travis:
  secure:
    BINSTAR_TOKEN: BBqNbpct42x7Ina0INjfYiNNEPVOAbL3qqLFy6zBhc3Rk1rG7By7cahvyVuWn1CFSsDhk7xlTFjXcAN3QtycZjtxItdAl0zeWD9OZfQMFia7SrajforDSBAn9qkllmoAwqx7X2yRbYhCIYl+G3fRM+uJZluaU51bUkQCyzwm5dkDGCPicDYsYKBwCHyie5zJGX/Xaw9l8qNjnyqFd5Oclqz1Oc1QlNnIg8P5g/cWxiVDaH0roIT5zK0mP6u8S+pejpr3iJaWmCyxMRm3bOtj+d81kkypHst86emkvfFnGvFtEHFwjVxHR/SE+++vn9eVIDMpwFHCX3ZFTzbLp62SqpVufde7vs7fD1QVnjc1VOGnnYqtRWBOwLOksVCuAAptnd1VfJwdSPLb5U70ZvGDG9HgZY8j8CWm4mDwee78LE8ttdKB97QUtdz9cin/IjJIGW0w7MaFrkv527DkivsbYP2dOig5+VBdi+NJcaxOgBRhtE1Csi5XJPZjl5xcSHFwOYObGITLAyJKZnmKZ01K5iptTtnD9HgtvjhQj3VZhx+U1UoaUQWEstzo+/D4YkL4auHBOlTkBF14aOiZLPoIwqfFW4kQSphcI0EKnOOnEmUjV9Pszo3kBN28DRp3Y9tAJ99OZccqWCVM4/ISU0CrpI+aZaL5HuQCpkzPj97+25M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
